# Generated by Django 3.1.2 on 2020-10-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='creado',
            new_name='creacion',
        ),
    ]
